In [13]:
import pandas as pd
text_1 = "/Users/wangyijie/Visual_Studio_code/毕业论文项目/01文本抓取与预处理/2025_truth.csv"
text_2 = "/Users/wangyijie/Visual_Studio_code/毕业论文项目/01文本抓取与预处理/2025_truth2.csv"

df1 = pd.read_csv(text_1)
df2 = pd.read_csv(text_2)

print(df1)
print(df2)

     web-scraper-order                              web-scraper-start-url  \
0         1752019239-6  https://rollcall.com/factbase-twitter/?platfor...
1         1752019239-7  https://rollcall.com/factbase-twitter/?platfor...
2         1752019239-8  https://rollcall.com/factbase-twitter/?platfor...
3         1752019239-9  https://rollcall.com/factbase-twitter/?platfor...
4        1752019239-10  https://rollcall.com/factbase-twitter/?platfor...
...                ...                                                ...
3040   1752019239-3046  https://rollcall.com/factbase-twitter/?platfor...
3041   1752019239-3047  https://rollcall.com/factbase-twitter/?platfor...
3042   1752019239-3048  https://rollcall.com/factbase-twitter/?platfor...
3043   1752019239-3049  https://rollcall.com/factbase-twitter/?platfor...
3044   1752019239-3050  https://rollcall.com/factbase-twitter/?platfor...

                                date  \
0          July 7, 2025 @ 6:37 PM ET
1          July 7, 2025 @ 4:38 PM ET
2          July 7, 2025 @ 4:37 PM ET
3          July 7, 2025 @ 4:36 PM ET
4          July 7, 2025 @ 4:36 PM ET
...                              ...
3040   January 19, 2025 @ 8:38 AM ET
3041   January 19, 2025 @ 7:19 AM ET
3042   January 19, 2025 @ 7:03 AM ET
3043  January 18, 2025 @ 10:51 PM ET
3044  January 18, 2025 @ 10:19 PM ET

                                                   text
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
3040  RT: https://truthsocial.com/users/Momo64/statu...
3041  Hostages starting to come out today! Three won...
3042                                       SAVE TIKTOK!
3043                                                NaN
3044  What is going on with this totally corrupt New...

[3045 rows x 4 columns]
    web-scraper-order                              web-scraper-start-url  \
0        1753354145-1  https://rollcall.com/factbase/trump/topic/soci...
1        1753354145-2  https://rollcall.com/factbase/trump/topic/soci...
2        1753354145-3  https://rollcall.com/factbase/trump/topic/soci...
3        1753354145-4  https://rollcall.com/factbase/trump/topic/soci...
4        1753354145-5  https://rollcall.com/factbase/trump/topic/soci...
..                ...                                                ...
445    1753354145-446  https://rollcall.com/factbase/trump/topic/soci...
446    1753354145-447  https://rollcall.com/factbase/trump/topic/soci...
447    1753354145-448  https://rollcall.com/factbase/trump/topic/soci...
448    1753354145-449  https://rollcall.com/factbase/trump/topic/soci...
449    1753354145-450  https://rollcall.com/factbase/trump/topic/soci...

                            date  \
0    July 23, 2025 @ 11:10 PM ET
1                              •
2    July 23, 2025 @ 10:59 PM ET
3    July 23, 2025 @ 10:59 PM ET
4    July 23, 2025 @ 10:50 PM ET
..                           ...
445    July 1, 2025 @ 2:30 PM ET
446    July 1, 2025 @ 2:30 PM ET
447    July 1, 2025 @ 2:29 PM ET
448    July 1, 2025 @ 2:02 PM ET
449    July 1, 2025 @ 1:30 PM ET

                                                  text
0    https://www.thegatewaypundit.com/2025/07/just-...
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
445  Because of the Violence and Criminality I have...
446  I am thrilled to announce that I will be trave...
447  Almost all of our Great Republicans in the Uni...
448                                                NaN
449  RT @realamericasvoice👏 ROOM ERUPTS WITH APPLAU...

[450 rows x 4 columns]

In [17]:
from datetime import datetime

# 自定义函数：转换 "July 23, 2025 @ 11:10 PM ET" 为 datetime 对象   
def parse_custom_date(date_str):
    try:
        if pd.isna(date_str):
            return pd.NaT
        clean_str = str(date_str).replace('@', '').replace('ET', '').strip()
        return datetime.strptime(clean_str, '%B %d, %Y %I:%M %p')
    except Exception as e:
        print(f"日期解析失败：{date_str} -> {e}")
        return pd.NaT



# 假设日期列名为 'date'，如果不同请替换
df1['date_parsed'] = df1['date'].apply(parse_custom_date)
df2['date_parsed'] = df2['date'].apply(parse_custom_date)

# 筛选 df1 中 1月20日之后的数据
df1_filtered = df1[df1['date_parsed'] > pd.to_datetime('2025-01-20')]

# 筛选 df2 中 7月8日至7月20日之间的数据（包含）
start_date = pd.to_datetime('2025-07-08')
end_date = pd.to_datetime('2025-07-20')
df2_filtered = df2[(df2['date_parsed'] >= start_date) & (df2['date_parsed'] <= end_date)]

# 合并两个数据集并按日期排序
df_combined = pd.concat([df1_filtered, df2_filtered])
df_combined = df_combined.sort_values(by='date_parsed').reset_index(drop=True)

# 输出结果
print(df_combined.head())  # 显示前几行数据

Empty DataFrame
Columns: [web-scraper-order, web-scraper-start-url, date, text, source, date_parsed]
Index: []